name: Deployment Notification

on:
  pull_request:
    types: [ opened ]

jobs:
  deployment_notification:
    runs-on: ubuntu-latest
    name: Beland Unity-Renderer Deployment Notification
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@main
        with:
          message: |
            After the CI passes:

            - This branch can be previewed at https://play.beland.io/?renderer-branch=${{ github.head_ref }}
            - Code coverage report: [https://renderer-artifacts.beland.io/branch-coverage/${{ github.head_ref }}](https://renderer-artifacts.beland.io/branch-coverage/${{ github.head_ref }})

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
